name: "Install PNPM, Node.js, and dependencies"
description: "Run pnpm install"

runs:
  using: "composite"

  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: ./.tool-versions
        cache: "pnpm"
        registry-url: https://registry.npmjs.org

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --prefer-offline
